server:
  port: 8080

spring:
  datasource:
    #url: jdbc:h2:mem:droneDb;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS DRONES;
    url: jdbc:h2:./h2/droneDb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    #url: jdbc:h2:./h2/droneDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS DRONES;
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  h2:
    console.enabled: true
    console.path: /h2
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: update
  sql:
    init:
      mode: EMBEDDED