server:
  port: 8080
  servlet:
    context-path: /delivery-drones

spring:
  datasource:
    url: jdbc:h2:mem:droneDb
    #url: jdbc:h2:./h2/droneDb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
app:
  battery:
    check:
      schedule: 0/30 * * * * ?
    percentage:
      min: 25
